# Generated by Django 2.2.9 on 2020-02-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=255, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
