# Generated by Django 2.2.9 on 2020-02-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_product_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
